# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PokeapiDex' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokeapiDex
  pod 'Siesta', '>=1.0-rc.2'
  pod 'Siesta/UI', '>=1.0-rc.2'
  pod 'SwiftyJSON'

end
